### ISSUE TITLE
WebDriverWait until method missing

### ISSUE THREAD

**Issue by bharathc02** [RationaleEmotions/SimpleSe#1]
## Issue
SimpleSe breaks when creating PageObject while using Selenium 3.6.0.

## RCA

With Selenium 3.6.0, they have migrated usages of guava Functions `com.google.common.base.Function` to Java 8 Functions `java.util.function.Function`.
Refer [link](https://github.com/SeleniumHQ/selenium/blob/0e680bca1047d1809d142ce86f4c83f4cb30659d/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L203)

But SimpleSe resorts to using guava functions and breaks the execution in [line](https://github.com/RationaleEmotions/SimpleSe/blob/4db3c6eb0fd73da2032f1f6d5e2d86f027a4e58b/src/main/java/com/rationaleemotions/page/PageObject.java#L320) with the error,
`java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;`

## Solution
Upgrade the version of Selenium to 3.6.0 and resolve the conflicts of Guava Function calls.

**Comment by krmahadevan** [comment]
@bharathc02 - Please try again using [1.0.1](http://repo1.maven.org/maven2/com/rationaleemotions/simple-se-pageobjects/1.0.1/). This is now taken care of.

**Comment by bharathc02** [comment]
@krmahadevan Verified
